: - negate + ;
: ++ over + ;
: * 0 '++ rot 1 - loop + ;
: 2dup over over ;
: >= 2dup > rot = or ;
: <= 2dup < rot = or ;
: xor 2dup and invert rrot or and ;
: True -1 ;
: False 0 ;
: 0> 0 > ;
: empty '. ssize 1 - loop ;
